name: Cloud Integration Test
on:
  push:
    branches:
      - main
jobs:
  Firebase_Test_Lab:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v2
      - name: Setup JaVa
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Pub Get
        run: flutter pub get
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Run Android integration tests
        run: ./android_integration.sh
      - name: Run iOS integration tests
        run: ./android_integration.sh
